-- local EmailItem = {}
-- --[[
--     -- 邮件
-- ]]
-- --local fairy = require "lobby/lcore/fairygui"
-- local logger = require "lobby/lcore/logger"
-- local urlpathsCfg = require "lobby/lcore/urlpathsCfg"
-- local httpHelper = require "lobby/lcore/httpHelper"
-- local proto = require "lobby/scripts/proto/proto"
-- local dialog = require "lobby/lcore/dialog"
-- local errHelper = require "lobby/lcore/lobbyErrHelper"
-- local subrecordView = require "lobby/scripts/gameRecord/subrecordView"
-- local CS = _ENV.CS
-- local EmailView = {}
-- function EmailView.new()
--     if EmailView.unityViewNode then
--         logger.debug("EmailView ---------------------")
--     else
--         _ENV.thisMod:AddUIPackage("lobby/fui_email/lobby_email")
--         local viewObj = _ENV.thisMod:CreateUIObject("lobby_email", "emailView")
--         EmailView.unityViewNode = viewObj
--         lobbyView.viewNode:AddChild(EmailView.unityViewNode)
--         _ENV.thisMod:RegisterCleanup(
--             function()
--                 viewObj:Dispose()
--             end
--         )
--     end
--     EmailView:EmailView()
-- end
-- return EmailItem
